sudo: true
language: haskell

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

os:
  - linux
  - osx

matrix:
  include:

  # Cabal
  - ghc: 8.6.5

  # Stack
  - ghc: 8.6.5
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

install:
  - sh tools/install.sh

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal new-run gamgee-test --enable-tests -- --quickcheck-tests 200
    else
      stack test --system-ghc --ta "--quickcheck-tests 200"
    fi

after_success:
  - |
    if [ -n "$STACK_YAML" ]; then
      sh tools/attach-binary.sh
    fi

notifications:
  email: false
